-- The app's database schema as plain, sorted text: what every migration adds up to.
-- scripts/db-test.sh runs this after applying supabase/migrations/ to a fresh Postgres
-- and diffs it against the committed supabase/schema-snapshot.txt, so a PR that changes
-- the schema shows exactly how, and a migration that changes it by accident fails.
--
-- Why not `supabase gen types typescript`: it needs the Supabase CLI plus Docker (it
-- runs the postgres-meta image), and nothing in this app reads generated DB types (the
-- mobile app uses supabase-js for auth only; data goes through the backend). Why not
-- `pg_dump --schema-only`: its output changes with the pg_dump version and, since the
-- 2025 security releases, carries a random `\restrict` key per run. This query reads the
-- catalog through pg_get_*def, which stays put across the Postgres versions Supabase runs.
--
-- Scope: the public schema (the API surface), plus triggers that call a public function
-- (on_auth_user_created). Privileges are the EFFECTIVE ones for the three API roles, so
-- they match between these CI stubs and a real `supabase start` stack.
-- An empty search_path makes every name schema-qualified, whatever the session's was.
set search_path = '';
with
tbl as (
  select c.oid, c.relname, c.relkind, c.relrowsecurity, c.relforcerowsecurity
  from pg_class c
  where c.relnamespace = 'public'::pg_catalog.regnamespace
    and c.relkind in ('r', 'p', 'v', 'm')
    and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype = 'e')
),
fn as (
  select p.oid, p.proname, p.prokind, p.prosecdef, p.provolatile, p.proconfig, p.prosrc,
         l.lanname, pg_get_function_identity_arguments(p.oid) as args
  from pg_proc p join pg_language l on l.oid = p.prolang
  where p.pronamespace = 'public'::pg_catalog.regnamespace
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
),
roles(r) as (values ('anon'), ('authenticated'), ('service_role')),
line(k, txt) as (
  select relname || ' 0',
         case relkind when 'v' then 'view ' when 'm' then 'materialized view ' else 'table ' end
         || relname
         || case when relkind in ('r', 'p')
              then ' rls=' || case when relrowsecurity then 'on' else 'off' end
                   || case when relforcerowsecurity then ' force_rls=on' else '' end
              else ': ' || md5(pg_get_viewdef(oid)) end
  from tbl
  union all
  select t.relname || ' 1 ' || lpad(a.attnum::text, 4, '0'),
         '  column ' || a.attname || ' ' || format_type(a.atttypid, a.atttypmod)
         || case when a.attnotnull then ' not null' else '' end
         || coalesce(' default ' || pg_get_expr(ad.adbin, ad.adrelid), '')
         || case a.attidentity when 'a' then ' generated always as identity'
              when 'd' then ' generated by default as identity' else '' end
         || case when a.attgenerated = 's' then ' (generated)' else '' end
  from tbl t
  join pg_attribute a on a.attrelid = t.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef ad on ad.adrelid = t.oid and ad.adnum = a.attnum
  union all
  select t.relname || ' 2 ' || co.conname,
         '  constraint ' || co.conname || ': ' || pg_get_constraintdef(co.oid)
  from tbl t join pg_constraint co on co.conrelid = t.oid
  union all
  select t.relname || ' 3 ' || ic.relname,
         '  index ' || pg_get_indexdef(i.indexrelid)
  from tbl t
  join pg_index i on i.indrelid = t.oid
  join pg_class ic on ic.oid = i.indexrelid
  union all
  select t.relname || ' 4 ' || po.polname,
         '  policy ' || po.polname || ': '
         || case po.polcmd when 'r' then 'select' when 'a' then 'insert' when 'w' then 'update'
              when 'd' then 'delete' else 'all' end
         || case when po.polpermissive then '' else ' restrictive' end
         || ' to ' || coalesce((select string_agg(rolname, ',' order by rolname)
                                from pg_roles where oid = any (po.polroles)), 'public')
         || coalesce(' using ' || pg_get_expr(po.polqual, po.polrelid), '')
         || coalesce(' check ' || pg_get_expr(po.polwithcheck, po.polrelid), '')
  from tbl t join pg_policy po on po.polrelid = t.oid
  union all
  select t.relname || ' 5 ' || tg.tgname, '  trigger ' || pg_get_triggerdef(tg.oid)
  from tbl t join pg_trigger tg on tg.tgrelid = t.oid and not tg.tgisinternal
  union all
  select t.relname || ' 6 ' || r,
         '  grant ' || r || ': '
         || coalesce(nullif(concat_ws(',',
              case when has_table_privilege(r, t.oid, 'select') then 'select' end,
              case when has_table_privilege(r, t.oid, 'insert') then 'insert' end,
              case when has_table_privilege(r, t.oid, 'update') then 'update' end,
              case when has_table_privilege(r, t.oid, 'delete') then 'delete' end), ''), 'none')
  from tbl t cross join roles
  where exists (select 1 from pg_roles where rolname = r)
  union all
  select '~fn ' || f.proname || '(' || f.args || ') 0',
         case f.prokind when 'p' then 'procedure ' else 'function ' end
         || f.proname || '(' || f.args || ')'
         || coalesce(' returns ' || pg_get_function_result(f.oid), '')
         || ' language ' || f.lanname
         || case f.provolatile when 'i' then ' immutable' when 's' then ' stable' else '' end
         || case when f.prosecdef then ' security definer' else '' end
         || coalesce(' set ' || array_to_string(f.proconfig, ' set '), '')
         || ' body:' || md5(f.prosrc)
  from fn f
  union all
  select '~fn ' || f.proname || '(' || f.args || ') 1',
         '  execute: ' || coalesce(nullif(concat_ws(',',
           case when has_function_privilege('anon', f.oid, 'execute') then 'anon' end,
           case when has_function_privilege('authenticated', f.oid, 'execute') then 'authenticated' end,
           case when has_function_privilege('service_role', f.oid, 'execute') then 'service_role' end), ''), 'none')
  from fn f
  where exists (select 1 from pg_roles where rolname = 'anon')
  union all
  -- Triggers on other schemas' tables that call into public (auth.users -> handle_new_user).
  select '~trg ' || tg.tgname, 'trigger ' || pg_get_triggerdef(tg.oid)
  from pg_trigger tg join fn f on f.oid = tg.tgfoid
  where not tg.tgisinternal and tg.tgrelid not in (select oid from tbl)
  union all
  select '~type ' || ty.typname,
         'type ' || ty.typname || ' enum(' || (select string_agg(e.enumlabel, ',' order by e.enumsortorder)
                                           from pg_enum e where e.enumtypid = ty.oid) || ')'
  from pg_type ty
  where ty.typnamespace = 'public'::pg_catalog.regnamespace and ty.typtype = 'e'
)
select txt from line order by k collate "C";
