/**
 * The guardrail packs this app has turned on, from privacy/data-map.yaml → packs.
 * GENERATED by `python3 scripts/check_guardrails.py --write`; the check fails in CI
 * while this file and the data map disagree. What each pack does:
 * docs/privacy/GUARDRAILS.md.
 */
export type PackId = "baseline" | "location" | "minors" | "health" | "ugc" | "financial" | "biometric";

export const PACKS: readonly PackId[] = ["baseline"];

export function packOn(id: PackId): boolean {
  return PACKS.includes(id);
}
