  uploads: {
    choose: "Choose a photo",
    chooseAnother: "Choose another photo",
    chooseLabel: "Choose a photo to upload",
    preview: "The photo you chose",
    uploading: "Uploading your photo",
    uploaded: "Photo uploaded",
    unsupportedType: "That file type isn't supported. Choose a JPEG, PNG, WebP or HEIC photo.",
    emptyFile: "That photo looks empty. Choose another one.",
    tooLarge: "That photo is over {{mb}} MB. Choose a smaller one.",
    rejected: "That photo couldn't be accepted. Photos must be images under {{mb}} MB.",
    slowDown: "That's a lot of uploads at once. Wait a minute, then try again.",
    failed: "The upload didn't finish. Check your connection and try again.",
  },
